version: "3.9"  # optional since v1.27.0
services:
  web1:
    image: opuzaman21/sample-flask-app:01
  web2:
    image: opuzaman21/sample-flask-app:01
  web3:
    image: opuzaman21/sample-flask-app:01
  load-balancer:
    image: nginx
    ports:
      - "8090:80"
    volumes:
      - /Users/opuzaman/githome/docker-containers/sample-nginx-load-balancer/load-balancer/conf.d/:/etc/nginx/conf.d